language: node_js
node_js:
  - 'node'

before_install:
  - rvm install 2.2.2

install:
  - npm install --global awesome-lint
  - gem install awesome_bot

script:
  - awesome-lint
  - awesome_bot README.md
