name: Check URL Redirects

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  check_redirects:
    runs-on: ubuntu-latest
    name: Check Redirects
    steps:
    - uses: actions/checkout@v6
    
    - name: Check redirects
      uses: ./.github/actions/url-redirect
      with:
        file: README.md
        redirect_fail: false
